### ISSUE TITLE
报名通道 - 后端 - 名额4

### ISSUE THREAD

**Issue by ahangchen** [scut-githuber/os_gui_backend#1]
直接按照群邮格式回复，不要回复实名或者其他个人信息

需要熟悉后端开发，java或php或python

**Comment by ahangchen** [comment]
537-cwh

**Comment by tingjiaqi123** [comment]
725-HJT

**Comment by joyxee** [comment]
531-cjx

**Comment by Saberko** [comment]
534-cd

**Comment by ahangchen** [comment]
已满4人，其他同学可以看看[用例分析组](https://github.com/scut-githuber/os-example)和[GUI组的产品/测试](https://github.com/scut-githuber/os-gui-front/issues/1)
