### ISSUE TITLE
登录注册

### ISSUE THREAD

**Issue by ahangchen** [scut-githuber/os_gui_backend#17]
基于LGUser表，设计/编写/实现  登录接口，注册接口，暂时不做找回密码接口。

**Comment by joyxee** [comment]
登录：
请求地址：/login/in/
方法：post
参数：{"_username":"用户名","_password":"前端hash后的密码"}
返回：成功时{"status":"success"}，失败时{"status":"fail","reason":"失败的原因，如密码错误等"}

注销：
请求地址：/login/out/
方法：get
返回：成功时{"status":"success"}，失败时{"status":"fail","reason":"失败的原因，如密码错误等"}

注册：
请求地址：/login/register/
方法：post
参数：{"_username":"用户名","_password":"前端hash后的密码","_email":"邮箱地址"}
（ps：后台不验证参数的合法性，如密码长度、邮箱地址的格式等等）
返回：成功时{"status":"success"}，失败时{"status":"fail","reason":"失败的原因，如用户名已被注册等"}

**Comment by ahangchen** [comment]
@joyxee  status改为err，reason改为msg，统一接口

**Comment by joyxee** [comment]
ok ,主要是刚刚码的时候还未看到你发的接口规范(>﹏<。)～

**Comment by joyxee** [comment]
## 登录
- /login/
- GET
- 返回：
  - 如果未登录
    - JSON：{“err”:err,”csrftoken”:csrftoken}
      - err：0
      - csrftoken：防御跨站域请求伪造的token，post到后台的时候需要用到
  - 如果已经登录（后台会记录session）
    - JSON：{“err”:err }
      - err：2
- POST
- 参数：
  - _username：账号、用户名
  - _password：前端hash后的密码
- 头部（必须设置，否则不能跨域提交请求）：
  - 'Content-Type':'application/json'
  - 'X-CSRFToken':通过上面get方法获取的csrftoken
- 返回：
  - 成功：
    - JSON：{"err": err}
      - err：1
  - 失败：
    - JSON：{"err": err, "msg": msg}
      - err：-1/-2/-3
      - msg：account_disabled/ wrong_password/sql_exception

## 注销
- /logout/
- GET
- 返回：
  - 成功：
    - JSON：{"err": err}
      - err：1
  - 失败：
    - JSON：{"err": err, "msg": msg}
      - err：-3
      - msg：sql_exception

## 注册
- /register/
- GET
- 返回：
  - JSON：{“err”:err,”csrftoken”:csrftoken}
    - err：0
    - csrftoken：防御跨站域请求伪造的token，post到后台的时候需要用到
- POST
- 参数：
  - _username： 账号、用户名
  - _password：前端hash后的密码
  - _email：邮箱地址
- 头部（必须设置，否则不能跨域提交请求）：
  - 'Content-Type': 'application/json'
  - 'X-CSRFToken':通过上面get方法获取的csrftoken
- 返回：
  - 成功：
    - JSON：{"err": err}
      - err：1
  - 失败：
    - JSON：{"err": err, "msg": msg}
      - err：-1/-3
      - msg：username_registered/sql_exception
